# obake uses abseil headers, which require 10.13
c_stdlib_version:          # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
# avoid pulling in vs2022 due to incompatibility with clang <16
c_stdlib_version:          # [win]
  - 2019                   # [win]
