{% set version = "1.6" %}

package:
  name: dcgp-python
  version: {{ version }}

source:
  url: https://github.com/darioizzo/dcgp/archive/v{{ version }}.tar.gz
  sha256: 838c9b88f8ffaebaf7840f86db14552cddef02d21bdb74bc8b826e4a20372a97
  patches:
    - tokens_patch.diff  # [win]

build:
  number: 0
  skip: true  # [(win and py<35) or win32]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - clang  # [win]
    - ninja  # [win]
  host:
    - boost
    - boost-cpp
    - eigen
    - audi
    - pagmo-devel
    - pygmo
    - tbb-devel
    - obake-devel
    - symengine
    - python
    - numpy
  run:
    - {{ pin_compatible("boost", max_pin="x.x") }}
    - pyaudi
    - {{ pin_compatible("pygmo", max_pin="x.x") }}
    - {{ pin_compatible("symengine", max_pin="x.x") }}
    - python
    - {{ pin_compatible('numpy') }}
    - sympy
    - matplotlib-base
    - graphviz

about:
  home: http://darioizzo.github.io/dcgp/
  license: GPL v3 and LGPL v3
  license_file: LICENSE
  summary: Implementation of the differential CGP (Cartesian Genetic Programming)

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
