{% set version = "1.6" %}

package:
  name: dcgp-python
  version: {{ version }}

source:
  url: https://github.com/darioizzo/dcgp/archive/v{{ version }}.tar.gz
  sha256: 838c9b88f8ffaebaf7840f86db14552cddef02d21bdb74bc8b826e4a20372a97

build:
  number: 5
  skip: true  # [(win and py<35) or win32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]
    # see #23 for reasons; should be removed when pagmo gets the required fix
    - clang <16  # [win]
    - ninja      # [win]
  host:
    - pybind11
    - pybind11-abi
    - libboost-devel
    - eigen
    - audi
    - pagmo-devel
    - pygmo
    - tbb-devel
    - obake-devel
    - symengine
    - python
    - numpy
  run:
    - python
    - pyaudi
    - libabseil
    - symengine
    - pygmo
    - cloudpickle

about:
  home: http://darioizzo.github.io/dcgp/
  license: GPL-3.0-only OR LGPL-3.0-only
  license_file: LICENSE
  summary: Implementation of the differential CGP (Cartesian Genetic Programming)
  dev_url: https://github.com/darioizzo/dcgp

extra:
  recipe-maintainers:
    - darioizzo
