{% set version = "1.4.3" %}

package:
  name: dcgp-python
  version: {{ version }}

source:
  url: https://github.com/darioizzo/dcgp/archive/v{{ version }}.tar.gz
  sha256: 061380fd9e9731a3a743cf708f3b2547f34f0017f9d3d6372f0c85d2b58d82e8
  patches:
    - tokens_patch.diff  # [win]

build:
  number: 0
  skip: true  # [(win and py<35) or win32]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang      # [win]
    - ninja      # [win]
  host:
    - boost
    - boost-cpp
    - eigen
    - audi
    - pagmo
    - pygmo
    - tbb-devel
    - obake-devel
    - symengine
    - python
    - numpy
    - ipopt  # [unix]
    - gmp    # [unix]
    - mpir   # [win]
  run:
    - boost
    - pyaudi
    - pagmo
    - pygmo
    - {{ pin_compatible("symengine", max_pin="x.x") }}
    - python
    - {{ pin_compatible('numpy') }}
    - ipopt  # [unix]
    - gmp    # [unix]
    - mpir   # [win]

about:
  home: http://darioizzo.github.io/dcgp/
  license: GPL v3 and LGPL v3
  license_file: LICENSE
  summary: Implementation of the differential CGP (Cartesian Genetic Programming)

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
